package serina.gui;

import java.io.IOException;
import java.net.URL;
import java.util.Objects;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Pos;
import javafx.geometry.Rectangle2D;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.HBox;
import javafx.scene.layout.StackPane;
import javafx.scene.shape.Circle;

/**
 * Displays one message with its speaker's avatar image.
 */
public class DialogBox extends HBox {
    private static final double MESSAGE_WIDTH_RATIO = 0.76;

    @FXML
    private Label messageLabel;
    @FXML
    private StackPane avatarPlaceholder;
    @FXML
    private ImageView displayPicture;

    /**
     * Creates and loads one dialog box.
     */
    private DialogBox(String message, Image image) {
        URL dialogResource = Objects.requireNonNull(
                DialogBox.class.getResource("/view/DialogBox.fxml"),
                "DialogBox.fxml is missing");
        FXMLLoader fxmlLoader = new FXMLLoader(dialogResource);
        fxmlLoader.setController(this);
        fxmlLoader.setRoot(this);

        try {
            fxmlLoader.load();
        } catch (IOException e) {
            throw new IllegalStateException("Unable to load DialogBox.fxml", e);
        }

        messageLabel.setText(message);
        messageLabel.maxWidthProperty().bind(widthProperty().multiply(MESSAGE_WIDTH_RATIO));
        displayPicture.setImage(image);
        displayPicture.setViewport(createSquareViewport(image));
        displayPicture.setClip(new Circle(20, 20, 20));
    }

    /**
     * Creates a right-aligned dialog box for a user message.
     *
     * @param message Message entered by the user.
     * @param image Avatar representing the user.
     * @return User dialog box.
     */
    public static DialogBox createUserDialog(String message, Image image) {
        DialogBox dialogBox = new DialogBox(message, image);
        dialogBox.getStyleClass().add("user-dialog");
        dialogBox.messageLabel.getStyleClass().add("user-bubble");
        dialogBox.avatarPlaceholder.getStyleClass().add("user-avatar");
        return dialogBox;
    }

    /**
     * Creates a left-aligned dialog box for a Serina response.
     *
     * @param message Response generated by Serina.
     * @param image Avatar representing Serina.
     * @return Serina dialog box.
     */
    public static DialogBox createSerinaDialog(String message, Image image) {
        DialogBox dialogBox = new DialogBox(message, image);
        dialogBox.setAlignment(Pos.TOP_LEFT);
        dialogBox.getChildren().setAll(dialogBox.avatarPlaceholder, dialogBox.messageLabel);
        dialogBox.getStyleClass().add("serina-dialog");
        dialogBox.messageLabel.getStyleClass().add("serina-bubble");
        dialogBox.avatarPlaceholder.getStyleClass().add("serina-avatar");
        return dialogBox;
    }

    /**
     * Returns a centered square crop that prevents portrait images from being stretched.
     */
    private static Rectangle2D createSquareViewport(Image image) {
        double sideLength = Math.min(image.getWidth(), image.getHeight());
        double minimumX = (image.getWidth() - sideLength) / 2;
        double minimumY = (image.getHeight() - sideLength) / 2;
        return new Rectangle2D(minimumX, minimumY, sideLength, sideLength);
    }
}
