package serina.gui;

import java.io.IOException;
import java.net.URL;
import java.util.Objects;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Pos;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Priority;
import javafx.scene.layout.VBox;
import serina.ResponseMessage;
import serina.ResponseType;

/**
 * Displays one user command or one typed Serina response.
 */
public class DialogBox extends HBox {
    private static final double USER_MESSAGE_WIDTH_RATIO = 0.8;

    @FXML
    private Label messageLabel;
    @FXML
    private VBox messagePanel;
    @FXML
    private HBox severityHeading;
    @FXML
    private Label severityIcon;
    @FXML
    private Label severityLabel;

    /**
     * Creates and loads one dialog box.
     */
    private DialogBox(String message) {
        URL dialogResource = Objects.requireNonNull(
                DialogBox.class.getResource("/view/DialogBox.fxml"),
                "DialogBox.fxml is missing");
        FXMLLoader fxmlLoader = new FXMLLoader(dialogResource);
        fxmlLoader.setController(this);
        fxmlLoader.setRoot(this);

        try {
            fxmlLoader.load();
        } catch (IOException e) {
            throw new IllegalStateException("Unable to load DialogBox.fxml", e);
        }

        messageLabel.setText(message);
    }

    /**
     * Creates a right-aligned dialog box for a user message.
     *
     * @param message Message entered by the user.
     * @return User dialog box.
     */
    public static DialogBox createUserDialog(String message) {
        DialogBox dialogBox = new DialogBox(message);
        dialogBox.getStyleClass().add("user-dialog");
        dialogBox.messagePanel.getStyleClass().add("user-panel");
        dialogBox.messagePanel.maxWidthProperty().bind(
                dialogBox.widthProperty().multiply(USER_MESSAGE_WIDTH_RATIO));
        return dialogBox;
    }

    /**
     * Creates a left-aligned dialog box for a Serina response.
     *
     * @param message Typed response generated by Serina.
     * @return Serina dialog box.
     */
    public static DialogBox createSerinaDialog(ResponseMessage message) {
        DialogBox dialogBox = new DialogBox(message.getText());
        dialogBox.setAlignment(Pos.TOP_LEFT);
        dialogBox.getStyleClass().add("serina-dialog");
        dialogBox.messagePanel.getStyleClass().add("serina-panel");
        HBox.setHgrow(dialogBox.messagePanel, Priority.ALWAYS);
        dialogBox.messagePanel.setMaxWidth(Double.MAX_VALUE);
        dialogBox.applyResponseType(message.getType());
        return dialogBox;
    }

    /**
     * Applies visible, textual severity information to non-normal responses.
     */
    private void applyResponseType(ResponseType responseType) {
        if (responseType == ResponseType.NORMAL) {
            return;
        }

        severityHeading.setManaged(true);
        severityHeading.setVisible(true);
        severityIcon.setText("!");

        if (responseType == ResponseType.ERROR) {
            severityLabel.setText("Error");
            messagePanel.getStyleClass().add("error-panel");
        } else {
            severityLabel.setText("Warning");
            messagePanel.getStyleClass().add("warning-panel");
        }
    }
}
