package serina.gui;

import java.util.Objects;

import javafx.application.Platform;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.TextField;
import javafx.scene.image.Image;
import javafx.scene.layout.VBox;
import serina.CommandResult;
import serina.Serina;

/**
 * Controls Serina's main chat window.
 */
public class MainWindow {
    private static final Image SERINA_IMAGE = loadImage("/images/serina-avatar.png");
    private static final Image USER_IMAGE = loadImage("/images/user-avatar.png");

    @FXML
    private ScrollPane scrollPane;
    @FXML
    private VBox dialogContainer;
    @FXML
    private TextField userInput;
    @FXML
    private Button sendButton;

    private Serina serina;

    /**
     * Creates the controller used by the main-window FXML document.
     */
    public MainWindow() {
    }

    /**
     * Initializes scrolling and input behavior after FXML fields are injected.
     */
    @FXML
    private void initialize() {
        dialogContainer.heightProperty().addListener((observable, oldHeight, newHeight) -> {
            scrollPane.setVvalue(1.0);
        });
        Platform.runLater(userInput::requestFocus);
    }

    /**
     * Injects Serina's command-processing backend and displays startup messages.
     *
     * @param serina Backend used to process commands.
     */
    public void setSerina(Serina serina) {
        this.serina = Objects.requireNonNull(serina);
        appendSerinaDialog(serina.getGreeting());
        for (String message : serina.getStartupMessages()) {
            appendSerinaDialog(message);
        }
    }

    /**
     * Sends the current input to Serina and appends the resulting dialog boxes.
     */
    @FXML
    private void handleUserInput() {
        String input = userInput.getText().trim();
        if (input.isEmpty()) {
            userInput.clear();
            userInput.requestFocus();
            return;
        }

        appendUserDialog(input);
        userInput.clear();

        CommandResult result = serina.executeCommand(input);
        for (String response : result.getResponses()) {
            appendSerinaDialog(response);
        }

        if (result.shouldExit()) {
            userInput.setDisable(true);
            sendButton.setDisable(true);
        } else {
            userInput.requestFocus();
        }
    }

    /**
     * Appends a message entered by the user.
     */
    private void appendUserDialog(String message) {
        dialogContainer.getChildren().add(DialogBox.createUserDialog(message, USER_IMAGE));
    }

    /**
     * Appends a response generated by Serina.
     */
    private void appendSerinaDialog(String message) {
        dialogContainer.getChildren().add(DialogBox.createSerinaDialog(message, SERINA_IMAGE));
    }

    /**
     * Loads an image packaged with the application.
     */
    private static Image loadImage(String resourcePath) {
        return new Image(Objects.requireNonNull(
                MainWindow.class.getResourceAsStream(resourcePath),
                "Image resource is missing: " + resourcePath));
    }
}
